; this is the normal shit
(tool-bar-mode -1)
(server-start)
(scroll-bar-mode -1)
(menu-bar-mode -1)
(show-paren-mode 1)
(setq inhibit-startup-screen t)
(global-display-line-numbers-mode t)
(set-fringe-mode 10)
(setq visual-bell t)
(setq display-line-numbers 'relative)
(column-number-mode t)
(set-face-attribute 'default nil :family "JetBrainsMono Nerd Font" :height 130)
(global-hl-line-mode t)
