theme = "carbonfox"

[editor]
line-number = "relative"
mouse = true
auto-pairs = true
auto-completion = true
auto-format = true
idle-timeout = 400
completion-trigger-len = 2

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

