[[language]]
name = "rust"
auto-format = true

[[language]]
name = "cpp"
auto-format = true
language-server = {command = "clangd"}

[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

